/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialogs;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import model.dao.CustomerDAO;
import model.work.Customer;

/**
 *
 * @author Anthony
 */
public class AddNewQuotationDialog extends javax.swing.JDialog {

    private DefaultComboBoxModel modelComboBoxCustomers = new DefaultComboBoxModel();
    private int numberSelectedCustomer;
    
    /**
     * Creates new form AddNewQuotationDialog
     */
    public AddNewQuotationDialog(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        this.jComboBoxCustomer.setModel(modelComboBoxCustomers);
        ArrayList<Customer> customers = CustomerDAO.getAll();
        customers.forEach(c -> {
            modelComboBoxCustomers.addElement(c);
        });
        numberSelectedCustomer=customers.get(0).getNumber();
    }

    public void UpdateComboBox() throws SQLException{
        for(int i=this.modelComboBoxCustomers.getSize()-1;i>=0;i--){
            this.modelComboBoxCustomers.removeElementAt(i);
        }
        ArrayList<Customer> customers = CustomerDAO.getAll();
        customers.forEach(c -> {
            modelComboBoxCustomers.addElement(c);
        });
    }
    
    public int getNumberSelectedCustomer() {
        return numberSelectedCustomer;
    }

    public void setNumberSelectedCustomer(int numberSelectedCustomer) {
        this.numberSelectedCustomer = numberSelectedCustomer;
    }

    public DefaultComboBoxModel getModelComboBoxCustomers() {
        return modelComboBoxCustomers;
    }
    
    public JButton getjButtonAddNewQuotation() {
        return jButtonAddNewQuotation;
    }

    public JComboBox<String> getjComboBoxCustomer() {
        return jComboBoxCustomer;
    }

    public JTextField getjTextFieldDate() {
        return jTextFieldDate;
    }

    public JTextField getjTextFieldPrice() {
        return jTextFieldPrice;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAddNewQuotation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxCustomer = new javax.swing.JComboBox<>();
        jTextFieldDate = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonAddNewQuotation.setText("Add new quotation");

        jLabel1.setText("Customer :");

        jLabel2.setText("Date :");

        jLabel3.setText("Price :");

        jComboBoxCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldDate.setText("date");

        jTextFieldPrice.setText("price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxCustomer, 0, 100, Short.MAX_VALUE)
                            .addComponent(jTextFieldDate)
                            .addComponent(jTextFieldPrice)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonAddNewQuotation)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAddNewQuotation)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddNewQuotation;
    private javax.swing.JComboBox<String> jComboBoxCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldPrice;
    // End of variables declaration//GEN-END:variables
}
